global:
  postgresql:
    auth:
      postgresPassword: 1234
      username: lect
      password: 1234
      database: lect
image.debug: true
primary:
  persistence:
    storageClass: nfs-client
  service:
    type: NodePort
    nodePorts:
      postgresql: 30033
volumePermissions:
  enabled: true