apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: lectapi
  name: lectapi
  namespace: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lectapi
  name: lectapi
  namespace: api
spec:
  replicas: 1 # do not change
  selector:
    matchLabels:
      app: lectapi
  template:
    metadata:
      labels:
        app: lectapi
      namespace: api
    spec:
      containers:
      - name: api
        image: lectmoh/api:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /app/data
          name: data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: lectapi
---
apiVersion: v1
kind: Service
metadata:
  name: lectapi
  namespace: api
spec:
  selector:
    app: lectapi
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
