apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: api
  labels:
    app: postgres
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: hadmin
  POSTGRES_PASSWORD: hadmin12!@
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: api
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15.2-alpine3.17
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgredb
          readOnly: false
      volumes:
      - name: postgredb
        persistentVolumeClaim:
          claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: api
spec:
  selector:
    app: postgres
  ports:
    - name: http
      port: 5432
      targetPort: 5432
      nodePort: 30081
  type: NodePort