spring:
  profiles:
    active: prod
   #main.web-application-type: none   #웹서버실행하지 않기
  mvc.pathmatch.matching-strategy: ant-path-matcher
  #shutdown  
  pid:
    file: /app/.app.pid
  jackson:
    time-zone: Asia/Seoul
      
  security:
    user:
      name: admin
      password: admin123!
      roles: ACTUATOR
    permit-addresses: "183.109.110.211, 172.30.1"  #쿠베 메니페스트 yml파일에서 처리는 나중에 필요에 따라서 처리한다.
    
springdoc:
#  swagger-ui:
#    enable: true
#  api-docs:
#    enabled: true
  date-time-format: yyyy-MM-dd HH:mm:ss
        
server:
  port: 8889
  servlet:
    context-path: /
    session:
      timeout: 28800000  # 8 hours in milliseconds
  jetty:     # Jetty 스레드 풀 설정
    threads:
      acceptors: -1 # Number of acceptor threads to use. When the value is -1, the default, the number of acceptors is derived from the operating environment.
      selectors: -1 # Number of selector threads to use. When the value is -1, the default, the number of selectors is derived from the operating environment.
      min: 2 # Minimum number of threads e.g. 8 
      max: 5 # Maximum number of threads e.g. 200
      #max-queue-capacity:  # Maximum capacity of the thread pool's backing queue. A default is computed based on the threading configuration.
      #idle-timeout:  # Maximum thread idle time in millisecond e.g. 60000ms      

#datasource id/pw 암호화 처리  : com/kware/common/config/JasyptConfig.java와 test source 참고하여 username, password를 암호화 처리할 수 있음 
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

hybrid:
  init-sql-location:
    ddl: classpath:/db/init/ddl.sql
    insert-data: classpath:/db/init/insert*.sql
  request:
    url: ${REQUEST_API_URL}  #쿠버네티스 yaml 설정
  my:
    callback-url: ${MY_CALLBACK_URL}  #쿠버네티스 yaml 설정
  collector:
    portal-api:
      url: ${PORTAL_API_URL}  #쿠버네티스 yaml 설정
      authorization: 9ed36fd5-4c9b-4fba-827c-84edac08637c 
      prometheus:
        authorization: "Basic YWRtaW46cXdlcjEyMzQhQCMk"
        unified_url: ${PROMETHEUS_URL}  #쿠버네티스 yaml 설정
      finish-enalbe: false
      delete-enalbe: false
    threads: 5
  scheduler:
    threads: 2
  datasource:
    url: jdbc:log4jdbc:postgresql://${POSTGRES_IP_PORT}/postgres?currentSchema=k_hybrid      #쿠버네티스 yaml 설정
    hikari: 
      jdbcUrl: ${hybrid.datasource.url}
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: ${POSTGRES_USERNAME}  #쿠버네티스 yaml 설정
      password: ${POSTGRES_PASSWORD}  #쿠버네티스 yaml 설정
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true  
  policy:
    resource-weights:
      ml:
        cpu: 4
        gpu: 2
        disk: 3
        memory: 4
      dl:
        cpu: 3
        gpu: 5
        disk: 3
        memory: 4
      inf:
        cpu: 4
        gpu: 2
        disk: 3
        memory: 3
    exclude-namespaces: "string|monitoring|kube-system|calico-.+|tigera-.+|ingress-.+|gpu-operator"
    datasource:
      hikari: 
        jdbcUrl: jdbc:log4jdbc:h2:tcp://localhost:9093/mem:policydb
        #jdbcUrl: jdbc:log4jdbc:h2:mem:policydb
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: sa
        password: 1234
        pool-name: hikari-cp
        maximum-pool-size: 10
        minimum-idle: 2
        data-source-properties: 
            cachePrepStmts: true
            prepStmtCacheSize: 250
            prepStmtCacheSqlLimit: 2048
            useServerPrepStmts: true 
            