spring:
  application:
    name: dolphin
  profiles:
    active: prod
 #웹서버실행하지 않기   
  #main.web-application-type: none
  mvc.pathmatch.matching-strategy: ant-path-matcher
  devtools:
    livereload:
      enabled: true
          
server:
  port: 8888

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    
---

spring:
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  #shutdown  
  pid:
    file: ./.app.pid
    
dolphin:
  apps:
    home: /home/kware/crawler/hpai_batch/bootJars/dolphin2
    ports: [9501, 9502]
    host: 172.30.1.14
  datasource:
    url: jdbc:log4jdbc:postgresql://172.30.1.12:5433/postgres
    hikari: 
      jdbcUrl: ${dolphin.datasource.url}
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      username: ENC(HrVw3fiyCLDR948tKQhAejZAT9wpchPEpFFoJG3Y38HWipO+iLHob1pXaX1N+pXg)
      password: ENC(/MbRwpHCgQGTORq4/DsIej4lS47MVzdzdW8TPWEthKH+h6P/sCqbru9aLMqV+iQp)
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true  


logging:
  file:
    name: /home/kware/crawler/hpai_batch/bootJars/dolphin2/logs/dolpin.log
    pattern: logs/dolpin-%d{yyyy-MM-dd}-%i.log.gz
  pattern:
    console: "[%d{MMdd HH:mm:ss.SSS} %-1.1p] %C{1}:%4.4L- %m%n" 
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  appenders:
    rolling-file:
      name: RollingFile
      type: RollingFile
      fileName: ${logging.file.name}
      filePattern: ${logging.file.pattern}
      layout:
        pattern: "%d [%t] %-5level %logger{36} - %msg%n"
      policies:
        size-based:
          size: 10MB
      strategy:
        type: DefaultRolloverStrategy
        delete:
          basePath: logs
          maxDepth: 2
          ifFileName:
            glob: "logs/dolpin-*.log.gz"
          ifLastModified:
            age: 1000d
      compression:
        type: GzCompressAction
  level:
    root: WARN
    com.zaxxer.hikari: ERROR
    com.kware: DEBUG
    jdbc.resultsettable: ERROR
    jdbc.sqlonly: ERROR
    jdbc.sqltiming: DEBUG
    org.springframework.web: ERROR