#이 클래스를 사용하여 우선순위 클래스를 설정하고, 기본 즉 클래스를 설정하지 않으면 value 0이다.

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: criticalPriority
value: 1000000
globalDefault: false
description: "Critical priority for high-impact and urgent workloads"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: highPriority
value: 500000
globalDefault: false
description: "High priority for important workloads that are less urgent than critical"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: mediumPriority
value: 100000
globalDefault: false
description: "Medium priority for standard workloads"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: lowPriority
value: 5000
globalDefault: false
description: "Low priority for non-essential workloads"

---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: veryLowPriority
value: 1000
globalDefault: false
description: "Very low priority for best-effort workloads with least impact on cluster"
