apiVersion: v1
kind: Namespace
metadata:
  name: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
  namespace: stress
  labels:
    app: cpu-stress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-stress
  template:
    metadata:
      labels:
        app: cpu-stress
    spec:
      nodeSelector: {}
      containers:
      - name: cpu-stress
        image: progrium/stress
        command:
          - /bin/sh
          - -c
          - stress --cpu 1 --vm 1 --vm-bytes 64M