apiVersion: v1
kind: Namespace
metadata:
  name: stress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  namespace: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      restartPolicy: Always
      containers:
      - name: alpine
        image: alpine
        command:
          - /bin/sh
          - "-c"
          - "sleep 60m"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "500m"
          limits:
            cpu: "500m"