apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybridoptimizer
  namespace: kware-product
  labels:
    app: hybridoptimizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hybridoptimizer
  template:
    metadata:
      labels:
        app: hybridoptimizer
    spec:
      containers:
        - name: hybridoptimizer
          image: rnd.kware.co.kr/hybridoptimizer:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8889
          env:
            - name: POSTGRES_IP_PORT
              value: "postgres-service:5432"
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: PORTAL_API_URL
              value: 'http://hybrid.strato.co.kr'
            - name: MY_CALLBACK_URL
              value: 'http://hybrid.strato.co.kr:30008'
            - name: PROMETHEUS_URL
              value: 'http://hybrid.strato.co.kr:30138/'
            - name: REQUEST_API_URL
              value: 'http://yaml-manager-service.keti-product.svc.cluster.local:8080'
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
      volumes:
        - name: app-logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: kware-product
  name: hybridoptimizer-service
spec:
  type: LoadBalancer
  ports:
    - port: 8889
      targetPort: 8889
      nodePort: 30008
  selector:
    app: hybridoptimizer