# priority-classes.yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hy-critical-priority
value: 1000000
globalDefault: false
description: "Critical priority for high-impact and urgent workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hy-high-priority
value: 500000
globalDefault: false
description: "High priority for important workloads that are less urgent than critical"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hy-medium-priority
value: 100000
globalDefault: false
description: "Medium priority for standard workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hy-low-priority
value: 5000
globalDefault: false
description: "Low priority for non-essential workloads"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: hy-verylow-priority
value: 1000
globalDefault: false
description: "Very low priority for best-effort workloads with least impact on cluster"