spring:
  profiles:
    active: prod
   #main.web-application-type: none   #웹서버실행하지 않기
  mvc.pathmatch.matching-strategy: ant-path-matcher
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
  #shutdown  
  pid:
    file: /app/bin/.app.pid
  jackson:
    time-zone: Asia/Seoul
    #serialization.WRITE_DATES_AS_TIMESTAMPS: false
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 80 #8888
  servlet:
    context-path: /
    session:
      timeout: 28800000  # 8 hours in milliseconds

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

hybrid:
  proxy:
     url: ${OPTIMIZER_API_URL}
  init-sql-location:
    ddl: classpath:/db/init/ddl.sql
    insert-data: classpath:/db/init/insert*.sql
  datasource:
    url: jdbc:log4jdbc:postgresql://${POSTGRES_IP_PORT}/postgres?currentSchema=k_hybrid      #쿠버네티스 yaml 설정
    hikari: 
      jdbcUrl: ${hybrid.datasource.url}
      driver-class-name: net.sf.log4jdbc.DriverSpy
      username: ${POSTGRES_USERNAME}  #쿠버네티스 yaml 설정
      password: ${POSTGRES_PASSWORD}  #쿠버네티스 yaml 설정
      pool-name: hikari-cp
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties: 
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true  
