apiVersion: v1
kind: Service
metadata:
  name: svc-tespring
spec:
  selector:
    app: po-tespring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort