prometheus:
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
        - job_name: lect-metrics
          scrape_interval: 15s
          metrics_path: /metrics
          scheme: http
          kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
              - monitoring
          relabel_configs:
          - source_labels: [__meta_kubernetes_pod_node_name]
            action: replace
            target_label: node
