apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-prometheus
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
    nodePort: 30090
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  sessionAffinity: ClientIP
  type: NodePort
